# Generated by Django 4.2.1 on 2023-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('sales', 'sales'), ('support', 'support'), ('staff', 'staff')], max_length=25),
        ),
    ]
