# Generated by Django 4.2.1 on 2023-05-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_clients_contract_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
