# Generated by Django 4.2.1 on 2023-05-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='existing',
            field=models.BooleanField(default=False),
        ),
    ]
