# Generated by Django 4.2.1 on 2023-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_client_existing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='value',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='time_created',
            new_name='date_creation',
        ),
        migrations.AddField(
            model_name='contract',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_due',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
